### ISSUE TITLE
Pygfx support

### ISSUE THREAD

**Issue by Korijn** [pygfx/pylinalg#6]
This checklist serves to track how far along we are to providing all the linalg operations pygfx requires. We would need to cross off all items on this list before we can make pygfx depend on pylinalg.

Additionally, keep in mind that the API we implement here is very different from the one currently in use in pygfx, so it would also require refactoring in pylinalg.

# pygfx checklist

Note: The names in this list are taken from pygfx, and do not correspond directly to the function names in pylinalg.

In many cases we don't even need to implement anything directly, since numpy already provides the required functionality directly, and LinalgBase wraps the functionality appropriately.

- [x] Matrix4
  - [x] get_inverse(matrix)
  - [x] set(matrix)
  - [x] make_orthographic(left, right, top, bottom, near, far)
    - [x] support depth ranges (-1..1 and 0..1) #8
  - [x] ~premultiply(matrix)~
  - [x] look_at(eye, target, up) #9
  - [x] multiply_matrices(matrix, matrix)
  - [x] compose(position, rotation, scaling)
  - [x] decompose(position, rotation, scaling)
  - [x] copy()
- [x] Vector3
  - [x] clone()
  - [x] add(vector)
  - [x] sub(vector)
  - [x] copy(vector)
  - [x] multiply(vector)
  - [x] add_scaled_vector(vector)
  - [x] normalize()
  - [x] negate()
  - [x] project(camera) #11
  - [x] unproject(camera) #12
  - [x] multiply_scalar(scalar)
  - [x] apply_quaternion(quaternion) #13
  - [x] set_from_spherical() #15
  - [x] distance_to(vector) #16
  - [x] length()
  - [x] dot(vector)
  - [x] cross(vector)
  - [x] set_from_matrix_position(matrix) #17
  - [x] apply_matrix(matrix)
- [x] Spherical
  - [x] set_from_vector(vector) #14
  - [x] make_safe() #18
- [x] Quaternion
  - [x] set_from_unit_vectors(vector, vector)
  - [x] clone()
  - [x] inverse()
  - [x] set_from_rotation_matrix()
  - [x] set_from_axis_angle(vector, angle)
  - [x] ~premultiply(quaternion)~
  - [x] multiply(quaternion)
- [x] Misc
  - [x] aabb_to_sphere #19
  - [x] transform
  - [x] transform_aabb #20

**Comment by Korijn** [comment]
@FirefoxMetzger technically we should now be able to:

* do to a release of pylinalg
* in pygfx:
  * remove the pygfx.linalg subpackage
  * refactor all broken code to use pylinalg

**Comment by almarklein** [comment]
What about the object API? I thought the idea was to leverage that in pygfx?

**Comment by FirefoxMetzger** [comment]
@Korijn I was about to ask here how we wish to proceed after having merged all the PRs. Do you want to release the functional API and then rewrite pygfx, or would you prefer to first discuss and complete the object API and then rewrite pygfx using transform objects?

**Comment by Korijn** [comment]
That's a step 2 in my mind. It's a lot more far reaching and impactful of a change to pygfx, and is not what I had in mind for pylinalg originally.

I'm fine with picking up that work as well now, I can see the benefits and how it is an exciting piece of the puzzle here. But I would really want to see some evidence that we're going to have a clean, elegant design that can be unit tested here in the pylinalg repo, including hierarchical transform capabilities, while not making it frustrating to adopt in pygfx.

**Comment by Korijn** [comment]
I'll try to "reboot" that whole topic in #21.

**Comment by FirefoxMetzger** [comment]
I see two paths in this case:

1. You or @almarklein release a new pylinalg version (I don't have access), and I begin working on the integration in pygfx.
2. We discuss the new objects API and I work on this one next.

I would like to avoid jumping back and forth because I think it will be slower than doing one first and then the other.
